# Generated by Django 5.2 on 2025-07-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(default='un', max_length=20)),
                ('categoria', models.CharField(choices=[('BEBIDA', 'Bebida'), ('INGREDIENTE', 'Ingrediente'), ('OUTRO', 'Outro')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
