# Generated by Django 5.2 on 2025-07-10 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_recebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='core.bar')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='core.restaurante')),
            ],
        ),
    ]
