# Generated by Django 5.2 on 2025-07-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contagembar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contagembar',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='contagembar',
            name='quantidade_doses_restantes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='contagembar',
            name='quantidade_garrafas_cheias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='doses_por_garrafa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('DESTILADO', 'Destilado'), ('CERVEJA', 'Cerveja'), ('VINHO', 'Vinho'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
