# Generated by Django 5.2 on 2025-07-14 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_contagembar_quantidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bar')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
