# Generated by Django 5.2 on 2025-07-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_requisicaoproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bar')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'unique_together': {('bar', 'produto')},
            },
        ),
    ]
