# Generated by Django 5.2.4 on 2025-07-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_requisicaoproduto_status_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permitidos', to='core.bar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bares_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bar')},
            },
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
