# Generated by Django 5.2.4 on 2025-07-23 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_barusuario_delete_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoUsuarioBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bares', models.ManyToManyField(to='core.bar')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_bar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BarUsuario',
        ),
    ]
