# Generated by Django 5.2.4 on 2025-08-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_permissaopagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaopagina',
            name='nome_pagina',
            field=models.CharField(choices=[('contagem', 'Contagem'), ('transferencias', 'Transferências'), ('eventos', 'Eventos'), ('requisicoes', 'Requisições'), ('aprovacao', 'Aprovacao'), ('historicos', 'Históricos'), ('relatorios', 'Relatórios')], max_length=50),
        ),
    ]
