# Generated by Django 5.2.4 on 2025-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_permissaopagina_nome_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaopagina',
            name='nome_pagina',
            field=models.CharField(choices=[('contagem', 'Contagem'), ('transferencias', 'Transferências'), ('eventos', 'Eventos'), ('requisicoes', 'Requisições'), ('aprovacao', 'Aprovacao'), ('historico_cont', 'Histórico_cont'), ('historico_requi', 'Historico_requi'), ('historico_transf', 'Historico_transf'), ('relatorios', 'Relatórios')], max_length=50),
        ),
    ]
