# Generated by Django 5.2.4 on 2025-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_permissaopagina_nome_pagina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoquebar',
            old_name='quantidade',
            new_name='quantidade_doses',
        ),
        migrations.AddField(
            model_name='estoquebar',
            name='quantidade_garrafas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
