# Generated by Django 5.2.4 on 2025-08-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_permissaopagina_nome_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaoproduto',
            name='data_decisao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaoproduto',
            name='motivo_negativa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
