# Generated by Django 5.2.4 on 2025-08-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_requisicaoproduto_data_decisao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horas',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero_pessoas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
