# Generated by Django 5.2.4 on 2025-08-13 19:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_evento_horas_evento_numero_pessoas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('unidade', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo'), ('g', 'Grama'), ('porcao', 'Porção'), ('l', 'Litro'), ('ml', 'Mililitro')], default='un', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.alimento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='core.evento')),
            ],
        ),
    ]
