# Generated by Django 5.2.4 on 2025-08-13 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alimento_eventoalimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='evento',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=12),
        ),
        migrations.AddField(
            model_name='evento',
            name='supervisor_finalizou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_finalizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
