# Generated by Django 5.2.4 on 2025-08-14 18:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_produto_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerdaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garrafas', models.PositiveIntegerField(default=0)),
                ('doses', models.PositiveIntegerField(default=0)),
                ('motivo', models.CharField(choices=[('QUEBRA', 'Quebra de garrafa'), ('DERRAMAMENTO', 'Derramamento'), ('SOBRA', 'Descarte de sobra'), ('QUALIDADE', 'Produto impróprio'), ('OUTRO', 'Outro')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('estoque_antes_garrafas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estoque_antes_doses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estoque_depois_garrafas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estoque_depois_doses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdas', to='core.bar')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perdas', to='core.produto')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdas', to='core.restaurante')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
