# Generated by Django 5.2.4 on 2025-08-19 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_perdaproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='baixado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='baixado_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='baixado_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evento',
            name='baixado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_baixados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data_evento', 'baixado_estoque'], name='core_evento_data_ev_78d187_idx'),
        ),
    ]
