# Generated by Django 5.2.4 on 2025-08-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_evento_baixado_em_evento_baixado_estoque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perdaproduto',
            name='baixado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perdaproduto',
            name='baixado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perdaproduto',
            name='baixado_obs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perdaproduto',
            name='baixado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdas_baixadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='perdaproduto',
            index=models.Index(fields=['baixado', 'data_registro'], name='core_perdap_baixado_aac231_idx'),
        ),
    ]
