# Generated by Django 5.2.4 on 2025-08-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_alimento_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoquebar',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='estoquebar',
            index=models.Index(fields=['bar', 'produto'], name='core_estoqu_bar_id_815748_idx'),
        ),
        migrations.AddConstraint(
            model_name='estoquebar',
            constraint=models.UniqueConstraint(fields=('bar', 'produto'), name='uniq_estoque_bar_produto'),
        ),
    ]
