# Generated by Django 5.2.4 on 2025-08-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_estoquebar_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquebar',
            options={'ordering': ['bar__nome', 'produto__nome']},
        ),
    ]
