# Generated by Django 5.2.4 on 2025-08-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_alimento_nome_and_more'),
        ('core', '0028_alter_estoquebar_unique_together_and_more'),
    ]

    operations = [
    ]
