# Generated by Django 5.2.4 on 2025-08-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_estoquebar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
    ]
