# Generated by Django 5.2.4 on 2025-08-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_permissaopagina_nome_pagina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquebar',
            options={'ordering': ['bar__nome', 'produto__nome']},
        ),
    ]
