# Generated by Django 5.2.4 on 2025-09-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_permissaopagina_nome_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.restaurante'),
        ),
    ]
