# Generated by Django 5.2.4 on 2025-08-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_estoquebar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquebar',
            options={},
        ),
    ]
