# Generated by Django 5.2.4 on 2025-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_recebimentoestoque_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaopagina',
            name='nome_pagina',
            field=models.CharField(choices=[('contagem', 'Contagem'), ('transferencias', 'Transferências'), ('eventos', 'Eventos'), ('requisicoes', 'Requisições'), ('aprovacao', 'Aprovacao'), ('historico_cont', 'Histórico_cont'), ('historico_requi', 'Historico_requi'), ('historico_transf', 'Historico_transf'), ('historico_entrada', 'Historico_entrada'), ('relatorios', 'Relatórios'), ('entrada_mercadoria', 'Entrada_mercadoria'), ('importacao', 'Importacao')], max_length=50),
        ),
    ]
