# Generated by Django 5.2.4 on 2025-09-02 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_permissaopagina_nome_pagina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recebimentoestoque',
            index=models.Index(fields=['restaurante', 'data_recebimento'], name='ix_receb_rest_data'),
        ),
    ]
