# Generated by Django 5.2.4 on 2025-09-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_estoquebar_options'),
        ('core', '0035_recebimentoestoque_ix_receb_rest_data'),
    ]

    operations = [
    ]
