# Generated by Django 5.2.4 on 2025-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_recebimentoestoque_ix_receb_rest_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estoquebar',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_garrafas__gte', 0), ('quantidade_doses__gte', 0)), name='chk_estoque_nao_negativo'),
        ),
    ]
