# Generated by Django 5.2.4 on 2025-09-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_estoquebar_chk_estoque_nao_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dose_padrao_ml',
            field=models.PositiveIntegerField(default=50, help_text='Tamanho da dose padrão em mL (padrão 50)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='volume_garrafa_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Ex.: 700, 750, 770, 1000, 1750', null=True),
        ),
    ]
