# Generated by Django 5.2.4 on 2025-09-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_estoquebar_chk_estoque_nao_negativo'),
        ('core', '0036_merge_20250902_1716'),
    ]

    operations = [
    ]
