# Generated by Django 5.2.4 on 2025-09-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20250909_1543'),
        ('core', '0037_produto_dose_padrao_ml_produto_volume_garrafa_ml'),
    ]

    operations = [
    ]
