# Generated by Django 5.2.4 on 2025-09-19 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20250911_1423'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquebar',
            options={'ordering': ['bar__nome', 'produto__nome']},
        ),
        migrations.AlterModelOptions(
            name='recebimentoestoque',
            options={'ordering': ['-data_recebimento'], 'verbose_name': 'Recebimento de estoque', 'verbose_name_plural': 'Recebimentos de estoque'},
        ),
        migrations.RemoveIndex(
            model_name='recebimentoestoque',
            name='ix_receb_rest_data',
        ),
        migrations.AlterField(
            model_name='permissaopagina',
            name='nome_pagina',
            field=models.CharField(choices=[('contagem', 'Contagem'), ('transferencias', 'Transferências'), ('eventos', 'Eventos'), ('requisicoes', 'Requisições'), ('aprovacao', 'Aprovacao'), ('historico_cont', 'Histórico_cont'), ('historico_requi', 'Historico_requi'), ('historico_transf', 'Historico_transf'), ('historico_entrada', 'Historico_entrada'), ('relatorios', 'Relatórios'), ('entrada_mercadoria', 'Entrada_mercadoria'), ('importacao', 'Importacao')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='contagembar',
            index=models.Index(fields=['bar', 'produto', '-data_contagem'], name='core_contag_bar_id_20bded_idx'),
        ),
        migrations.AddIndex(
            model_name='recebimentoestoque',
            index=models.Index(fields=['restaurante', 'bar', 'data_recebimento'], name='ix_receb_rest_bar_data'),
        ),
        migrations.AddIndex(
            model_name='recebimentoestoque',
            index=models.Index(fields=['produto'], name='ix_receb_produto'),
        ),
    ]
