# Generated by Django 5.2.4 on 2025-09-19 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_estoquebar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recebimentoestoque',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='contagembar',
            name='core_contag_bar_id_20bded_idx',
        ),
        migrations.RemoveIndex(
            model_name='recebimentoestoque',
            name='ix_receb_rest_bar_data',
        ),
        migrations.RemoveIndex(
            model_name='recebimentoestoque',
            name='ix_receb_produto',
        ),
        migrations.AddIndex(
            model_name='recebimentoestoque',
            index=models.Index(fields=['restaurante', 'data_recebimento'], name='ix_receb_rest_data'),
        ),
    ]
