# Generated by Django 5.2.4 on 2025-09-22 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_recebimentoestoque_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contagembar',
            options={'ordering': ['-data_contagem']},
        ),
        migrations.AlterModelOptions(
            name='recebimentoestoque',
            options={'ordering': ['-data_recebimento']},
        ),
        migrations.AddIndex(
            model_name='bar',
            index=models.Index(fields=['restaurante', 'is_estoque_central'], name='ix_bar_rest_iscentral'),
        ),
        migrations.AddIndex(
            model_name='contagembar',
            index=models.Index(fields=['bar', 'produto', '-data_contagem'], name='ix_cont_bar_prod_dt_desc'),
        ),
        migrations.AddIndex(
            model_name='contagembar',
            index=models.Index(fields=['produto', '-data_contagem'], name='ix_cont_prod_dt_desc'),
        ),
        migrations.AddIndex(
            model_name='recebimentoestoque',
            index=models.Index(fields=['restaurante', 'bar', 'data_recebimento'], name='ix_receb_rest_bar_data'),
        ),
        migrations.AddIndex(
            model_name='recebimentoestoque',
            index=models.Index(fields=['produto'], name='ix_receb_produto'),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_estoque_central', True)), fields=('restaurante',), name='uniq_um_central_por_restaurante'),
        ),
    ]
